import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NotificationBar from "./components/homepage/NotificationBar";
import Navbar from "./components/globalComponents/Navbar";
import Footer from "./components/globalComponents/Footer";
import { WishlistProvider } from "./wishlist/ContextWishlist/WishlistContext";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "BANDAGE",
  description: "Generated by Aiman Ahsan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className="  text-[#252B42] ]">
        <header>
          <NotificationBar />
          <Navbar />
        </header>
    
      <WishlistProvider>   
      
        {children}
        
        </WishlistProvider> 
        
        
        
        <Footer />
      </body>
    </html>
  );
}
